# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180617_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-created_time',)},
        ),
    ]
