# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('now', models.PositiveIntegerField(default=0)),
                ('aim', models.PositiveIntegerField(default=1)),
                ('complete_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-complete_time'],
            },
        ),
    ]
